
language:
  - python
  - cpp

python:
  - "2.7"

compiler:
  - gcc

before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install ros-indigo-ros-base
  - sudo apt-get install ros-indigo-move-base
  - sudo apt-get install python-catkin-pkg python-empy python-rospkg
  - pip install catkin_pkg
  - pip install rospkg
  - sudo rosdep init
  - rosdep update
install:
  # make a workspace and checkout the right repos:
  - source /opt/ros/indigo/setup.bash
  - mkdir -p ~/catkin_ws/src
  - cd ~/catkin_ws/src
  - catkin_init_workspace
  - cd ..
  - catkin_make
  - cd ~/catkin_ws/src
  - ln -s $CI_SOURCE_PATH . # link repo under test.
before_script:
  - source ~/catkin_ws/devel/setup.bash
  - cd ~/catkin_ws/src
script:
  - cd ~/catkin_ws
  - catkin_make
